name: Deploy the code to the development stage

on:
  push:
    branches:
      - development

jobs:
  development-build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/prepare
      - run: yarn deploy:dev
        env:
          SERVERLESS_ACCESS_KEY: ${{ secrets.SERVERLESS_ACCESS_KEY }}
