name: Deploy the code to the production stage

on:
  push:
    branches:
      - main

jobs:
  production-build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/prepare
      - run: yarn deploy:prod
